### ISSUE TITLE
How'd you get these icons in the bottom right?

### ISSUE THREAD

**Issue by mbbroberg** [uroybd/topobon#29]
Hey @uroybd, I really enjoy your garden and I'm building my own. I can't seem to find a way to add the the email me or toggle for light/dark mode like you have on yours: 

<img width="99" alt="Screenshot 2024-05-05 at 1 01 02 PM" src="https://github.com/uroybd/topobon/assets/1744971/a2240d2e-8332-4857-871f-2cc98a429f73">

Could you explain where that is or what theme you used that includes it? Thanks!

**Comment by uroybd** [comment]
I'm using the Minimal theme. It has both the dark and light mode and I can leverage that.

This script contains the code for that floating control section: https://github.com/uroybd/topobon/blob/main/src%2Fsite%2F_includes%2Fcomponents%2Fuser%2Fcommon%2Ffooter%2F001-floatingControls.njk

**Comment by mbbroberg** [comment]
Thank you!
